function ...
[...
st_eirp_dbW, ...
path_loss, ...
gs_rx_pwr_db, ...
gs_g_to_t, ...
gs_s_to_no, ...
gs_rx_ebno, ...
system_link_margin_ebno, ...
gs_rx_snr, ...
system_link_margin_snr ...
] = downlink(...
             slant_range, ...
             tx_freq, ...
             st_tx_pwr_w, ...
             st_cable_loss, ...
             st_tx_antenna_gain_dbi, ...
             st_antenna_pointing_loss, ...
             st_polarization_loss, ...
             atmospheric_losses, ...
             ionoshperic_losses, ...
             rain_losses, ...
             gs_rx_pointing_loss, ...
             gs_rx_antenna_gain, ...
             gs_rx_line_loss, ...
             gs_rx_noise_temp, ...
             system_data_rate,...
             threshold_ebno, ...
             gs_rx_bw, ...
             threshold_snr...
             )
    %grond station
    
    st_eirp_dbW = 10*log10(st_tx_pwr_w) - st_cable_loss + st_tx_antenna_gain_dbi

    %uplink path
    path_loss = 22 + 20*log10((slant_range*1000)/((physconst('LightSpeed')/(tx_freq*10^6))))
    gs_rx_pwr_db = st_eirp_dbW - st_antenna_pointing_loss - rain_losses - ionoshperic_losses - atmospheric_losses - path_loss - st_polarization_loss

    %Earth station (ebno)
    gs_g_to_t = gs_rx_antenna_gain - gs_rx_line_loss - 10*log10(gs_rx_noise_temp)
    gs_s_to_no = gs_rx_pwr_db - gs_rx_pointing_loss + 228.6 + gs_g_to_t
    gs_rx_ebno = gs_s_to_no - 10*log10(system_data_rate)
    system_link_margin_ebno = gs_rx_ebno - threshold_ebno

    %Earth staion (snr)
    gs_rx_pwr_at_lna = gs_rx_pwr_db - gs_rx_pointing_loss + gs_rx_antenna_gain - gs_rx_line_loss
    gs_rx_np = -228.6 + 10*log10(gs_rx_bw) + 10*log10(gs_rx_noise_temp);
    gs_rx_snr = gs_rx_pwr_at_lna - gs_rx_np
    system_link_margin_snr = gs_rx_snr - threshold_snr
end