function ...
[...
gs_eirp_dbW, ...
path_loss, ...
st_rx_pwr_dB, ...
st_g_to_t, ...
st_s_to_no, ...
st_rx_ebno, ...
system_link_margin_ebno, ...
st_rx_snr, ...
system_link_margin_snr ...
] = uplink(slant_range, ...
                     tx_freq, ...
                     gs_tx_pwr_w, ...
                     gs_back_off_dB, ...
                     tx_cable_loss, ...
                     gs_tx_antenna_gain_dbi, ...
                     gs_antenna_pointing_loss, ...
                     gs_polarization_loss, ...
                     atmospheric_losses, ...
                     ionoshperic_losses, ...
                     rain_losses, ...
                     st_rx_pointing_loss, ...
                     st_rx_antenna_gain, ...
                     st_rx_line_loss, ...
                     st_rx_noise_temp, ...
                     system_data_rate,...
                     threshold_ebno, ...
                     st_rx_bw, ...
                     threshold_snr)
    %grond station
    
    gs_eirp_dbW = 10*log10(gs_tx_pwr_w) - gs_back_off_dB - tx_cable_loss + gs_tx_antenna_gain_dbi;

    %uplink path
    path_loss = 22 + 20*log10((slant_range*1000)/((physconst('LightSpeed')/(tx_freq*10^6))));
    st_rx_pwr_dB = gs_eirp_dbW - gs_antenna_pointing_loss - rain_losses - ionoshperic_losses - atmospheric_losses - path_loss - gs_polarization_loss;

    %satellite (ebno)
    st_g_to_t = st_rx_antenna_gain - st_rx_line_loss - 10*log10(st_rx_noise_temp);
    st_s_to_no = st_rx_pwr_dB - st_rx_pointing_loss + 228.6 + st_g_to_t;
    st_rx_ebno = st_s_to_no - 10*log10(system_data_rate);
    system_link_margin_ebno = st_rx_ebno - threshold_ebno;

    %satellite (snr)
    st_rx_pwr_at_lna = st_rx_pwr_dB - st_rx_pointing_loss + st_rx_antenna_gain - st_rx_line_loss
    st_rx_np = -228.6 + 10*log10(st_rx_bw) + 10*log10(st_rx_noise_temp)
    st_rx_snr = st_rx_pwr_at_lna - st_rx_np
    system_link_margin_snr = st_rx_snr - threshold_snr;
end